config/routes.rb
Rails.application.routes.draw do
  resources :rents, only: [:new, :index, :create]
  get 'users_rents', to: 'rents#users_index'
  post 'users_rents', to: 'rents#users_index'
  post 'rents_index', to: 'rents#index'

  post 'approve', to: 'rents#approve'
  post 'reject', to: 'rents#reject'
  post 'take', to: 'rents#take'
  post 'return', to: 'rents#return'
  resources :items, only: [:new, :index, :create, :edit, :destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :pages, only: [:show, :edit, :update]
  resources :events do
    resources :entries, only: [:create, :destroy] do
      put '/', to: 'entries#toggle_showed_up'
    end
  end
  resources :teams do
    resources :memberships do
      put '/approve', to: 'memberships#approve'
      delete '/decline', to: 'memberships#decline'
      delete '/destroy', to: 'memberships#destroy'
    end
  end
  resources :users, only: [:index, :show, :edit, :update] do
    post :set_animation, on: :collection
  end
  resources :articles
  resources :images, only: [:create]

  get '/', to: 'home#index'

  post '/logout', to: 'sessions#destroy', as: :logout
  get '/login', to: 'sessions#new', as: :login
  get '/auth/oauth/callback', to: 'sessions#create'

  scope :email do
    get '/login', to: 'session_with_email#login_page', as: :email_login_page
    post '/login', to: 'session_with_email#login', as: :email_login
    get '/registration', to: 'session_with_email#registration_page', as: :email_registration_page
    post '/registration', to: 'session_with_email#registration', as: :email_registration
  end
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root to: redirect('/')
end

app/controllers/session_with_email_controller.rb
require 'bcrypt'

class SessionWithEmailController < ApplicationController
  class LoginError < StandardError; end

  def login_page
    @user = User.new
  end

  def login
    @current_user = User.find_by(mail: params[:user][:mail])
    raise LoginError if @current_user.nil? || @current_user.auth_sch_id.present?
    password = BCrypt::Password.new(@current_user.password)
    raise LoginError unless password == params[:user][:password]
    session[:user_id] = @current_user.id
    redirect_to root_path
  rescue LoginError
    @user = User.new(login_params)
    flash[:notice] = "Hibás adatok!"
    render 'login_page'
  end

  def registration_page
    @user = User.new
  end

  def registration
    @user = User.new(registration_params)

    unless (params[:user][:password] == params[:user][:confirmation])
      flash[:notice] = "Jelszavak nem egyeznek"
      return render "registration_page"
    end
    return render "registration_page" unless @user.valid?
    @user.password = BCrypt::Password.create(@user.password)

    if (@user.save)
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @user.password = nil
      render :email_registration_new
    end
  end

  private

  def registration_params
    params.require(:user).permit(:mail, :password, :name)
  end

  def login_params
    params.require(:user).permit(:mail, :password)
  end
end

app/views/session_with_email/login_page.erb
<%= form_with(model: @user, local: true, url: email_login_page_url, class: 'ui form') do |form| %>
  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail %>
  </div>
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <%= form.submit 'Belépés', class: 'ui button primary' %>
<% end %>
<br/>
<%= link_to 'Regisztráció', email_registration_page_path , class: 'ui button secondary mt-3' %>

app/views/session_with_email/registration_page.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2> Az alábbi hibák léptek fel:</h2>

    <ul>
      <% @user.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true, url: email_registration_path, class: 'ui form') do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
  <%= form.label :mail %>
    <%= form.text_field :mail %>
  </div>
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div class="field">
    <%= form.label :confirmation %>
    <%= form.password_field :confirmation %>
  </div>
  <%= form.submit'Regisztráció', class: 'ui button primary' %>
<% end %>