config/routes.rb
Rails.application.routes.draw do
  resources :rents, only: [:new, :index, :create]
  get 'users_rents', to: 'rents#users_index'
  post 'users_rents', to: 'rents#users_index'
  post 'rents_index', to: 'rents#index'

  post 'approve', to: 'rents#approve'
  post 'reject', to: 'rents#reject'
  post 'take', to: 'rents#take'
  post 'return', to: 'rents#return'
  resources :items, only: [:new, :index, :create, :edit, :destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :pages, only: [:show, :edit, :update]
  resources :events do
    resources :entries, only: [:create, :destroy] do
      put '/', to: 'entries#toggle_showed_up'
    end
  end
  resources :teams do
    resources :memberships do
      put '/approve', to: 'memberships#approve'
      delete '/decline', to: 'memberships#decline'
      delete '/destroy', to: 'memberships#destroy'
    end
  end
  resources :users, only: [:index, :show, :edit, :update] do
    post :set_animation, on: :collection
  end
  resources :articles
  resources :images, only: [:create]

  get '/', to: 'home#index'

  post '/logout', to: 'sessions#destroy', as: :logout
  get '/login', to: 'sessions#new', as: :login
  get '/auth/oauth/callback', to: 'sessions#create'

  scope :email do
    get '/login', to: 'session_with_email#login_page', as: :email_login_page
    post '/login', to: 'session_with_email#login', as: :email_login
    get '/registration', to: 'session_with_email#registration_page', as: :email_registration_page
    post '/registration', to: 'session_with_email#registration', as: :email_registration
  end
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root to: redirect('/')
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :item
  belongs_to :user
  enum state: [:unprocessed, :approved, :rejected, :taken, :returned], _default: :unprocessed

  validates :begin, presence: true
  validate :begin_cant_be_before_the_present
  validates :end, presence: true , comparison: { greater_than: :begin, message: " később legyen, mint a kezdete." }
  validates :number, presence: true, comparison: { greater_than: 0 }
  validates_with RentNumberValidator


  def begin_cant_be_before_the_present
    if self.begin < Time.now
      errors.add(:begin, "később legyen, mint a mostani időpont.")
    end
  end

  #
  #STATE MACHINE
  def approve!
    raise Exceptions::ForbiddenTransition unless unprocessed?
    approved!
  end

  def reject!
    raise Exceptions::ForbiddenTransition unless unprocessed?
    rejected!
  end

  def take!
    raise Exceptions::ForbiddenTransition unless approved?
    taken!
  end

  def return!
    raise Exceptions::ForbiddenTransition unless taken?
    returned!
  end

  scope :desc, -> { order("rents.id DESC") }

  def self.filter(params)
    states = params.select{ |k,v| v == "1"}.keys
    Rent.where(state: states).desc
  end

  def self.users_filter(params, id)
    states = params.select{ |k,v| v == "1"}.keys
    Rent.where(user_id: id).where(state: states).desc
  end

  def item
    Item.unscoped { super }
  end

  def interval
    self.begin..self.end
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :require_admin, only: %i[ index approve reject take return ]
  before_action :require_login, only: %i[ new create users_index ]
  before_action :set_rent, only: %i[ show edit update destroy ]

  # GET /rents or /rents.json
  def index
    states = Rent.states.keys
    states.each {|state| params[state.to_sym] ="1"} unless params.keys.any?{|param| states.include?(param)}
    @rents = Rent.filter(rent_filter_params)
  end

  # GET /rents/1 or /rents/1.json
  def show
  end

  # GET /rents/new
  def new
    return redirect_to root_path if params[:item_id].nil?
    @rent = Rent.new
    @rent.item_id = params[:item_id]
  end

  # GET /rents/1/edit
  def edit
  end

  # POST /rents or /rents.json
  def create
    @rent = Rent.new(rent_params)

    respond_to do |format|
      if @rent.save
        format.html { redirect_to users_rents_url, notice: "Sikeres kölcsönzés." }
        format.json { render :show, status: :created, location: @rent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rents/1 or /rents/1.json
  def update
    respond_to do |format|
      if @rent.update(rent_params)
        format.html { redirect_to rent_url(@rent), notice: "Rent was successfully updated." }
        format.json { render :show, status: :ok, location: @rent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rents/1 or /rents/1.json
  def destroy
    @rent.destroy

    respond_to do |format|
      format.html { redirect_to rents_url, notice: "Rent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def approve
    rent = Rent.find(params[:rent])
    rent.approve!
    return redirect_to rents_path
  end

  def reject
    rent = Rent.find(params[:rent])
    rent.reject!
    return redirect_to rents_path
  end

  def take
    rent = Rent.find(params[:rent])
    rent.take!
    return redirect_to rents_path
  end

  def return
    rent = Rent.find(params[:rent])
    rent.return!
    return redirect_to rents_path
  end

  def users_index
    states = Rent.states.keys
    states.each {|state| params[state.to_sym] ="1"} unless params.keys.any?{|param| states.include?(param)}
    @rents = Rent.users_filter(rent_filter_params, current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rent
      @rent = Rent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rent_params
      params.require(:rent).permit(:item_id, :user_id, :begin, :end, :state, :number)
    end

  def rent_filter_params
    params.permit(:unprocessed, :approved, :rejected, :taken, :returned)
  end
end

app/helpers/rents_helper.rb
module RentsHelper
  def to_checked(string)
    string == "1" ? true : false
  end
end

app/views/rents/_form.html.erb
<% if @rent.errors.any? %>
  <div id="error_explanation">
    <h2> Az alábbi hibák léptek fel:</h2>

    <ul>
      <% @rent.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: rent, local: true, class: 'ui form') do |form| %>

  <div class="ui form">
    <div>
      <h5>Név</h5>
      <%= User.find(current_user.id).name %>
      <%= form.hidden_field :user_id, :value => current_user.id %>
    </div>

    <div>
      <h5>Eszköz</h5>
      <%= Item.find(@rent.item_id).name %>
      <%= form.hidden_field :item_id, :value => @rent.item_id %>
    </div>

    <div class="field">
      <%= form.label :number, 'Darabszám' %>
      <%= form.number_field :number %>
    </div>

    <div class="field">
      <%= form.label :begin, 'Kezdete' %>
      <%= form.datetime_field :begin %>
    </div>

    <div class="field">
      <%= form.label :end, 'Vége' %>
      <%= form.datetime_field :end %>
    </div>

    <div class="actions">
      <%= form.submit 'Mentés', class: 'ui button' %>
    </div>
<% end %>

app/views/rents/_rent.html.erb
<div id="<%= dom_id rent %>">
  <p>
    <strong>Item:</strong>
    <%= rent.item.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= rent.user.name %>
  </p>

  <p>
    <strong>Begin:</strong>
    <%= rent.begin %>
  </p>

  <p>
    <strong>End:</strong>
    <%= rent.end %>
  </p>

  <p>
    <strong>State:</strong>
    <%= rent.state %>
  </p>

</div>

app/views/rents/edit.html.erb
<h1>Editing rent</h1>

<%= render "form", rent: @rent %>

<br>

<div>
  <%= link_to "Show this rent", @rent %> |
  <%= link_to "Back to rents", rents_path %>
</div>

app/views/rents/index.html.erb
<h1>Kölcsönzések</h1>

<h3>Szűrés állapotra</h3>
<%= form_with url: "/rents_index", local: true do |form| %>
  <div class="container ui">
    <%= form.check_box :unprocessed, checked: to_checked(params[:unprocessed]) %>
    <%= form.label :unprocessed, "feldolgozatlan", class: 'item filteroption' %>

    <%= form.check_box :approved, checked: to_checked(params[:approved]) %>
    <%= form.label :approved, "engedélyezve", class: 'item filteroption' %>

    <%= form.check_box :rejected, checked: to_checked(params[:rejected]) %>
    <%= form.label :rejected, "elutasítva", class: 'item filteroption' %>

    <%= form.check_box :taken, checked: to_checked(params[:taken]) %>
    <%= form.label :taken, "kiadva", class: 'item filteroption' %>

    <%= form.check_box :returned, checked: to_checked(params[:returned]) %>
    <%= form.label :returned, "visszavéve", class: 'item filteroption' %>

  </div>
  <br>
  <%= form.submit "Szűrés", class: "ui button primary" %>
<% end %>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Név</th>
      <th>Eszköz</th>
      <th>Darabszám</th>
      <th>Kezdet</th>
      <th>Vége</th>
      <th>Állapot</th>
      <th>Műveletek</th>
    </tr>
  </thead>

  <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td><%= rent.user.name %></td>
        <td><%= rent.item.name %></td>
        <td><%= rent.number %> darab</td>
        <td><%= rent.begin.strftime("%Y.%m.%d. %H:%M") %></td>
        <td><%= rent.end.strftime("%Y.%m.%d. %H:%M") %></td>
        <td><%= I18n.t :"rent_states.#{rent.state}" %></td>
        <td><%= link_to 'Engedélyez', approve_path(:rent => rent), method: "approve", :class => "ui button primary" if rent.unprocessed? %>
        <%= link_to 'Elutasít', reject_path(:rent => rent), method: "reject", :class => "ui button negative" if rent.unprocessed? %>
        <%= link_to 'Kiad', take_path(:rent => rent), method: "take", :class => "ui button" if rent.approved? %>
        <%= link_to 'Visszavesz', return_path(:rent => rent), method: "return", :class => "ui button" if rent.taken? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rents/new.html.erb
<h1>Új kölcsönzés</h1>

<%= render "form", rent: @rent %>

app/views/rents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rent %>

<div>
  <%= link_to "Edit this rent", edit_rent_path(@rent) %> |
  <%= link_to "Back to rents", rents_path %>

  <%= button_to "Destroy this rent", @rent, method: :delete %>
</div>

app/views/rents/users_index.html.erb
<h1>Kölcsönzések</h1>

<h3>Szűrés állapotra</h3>
<%= form_with url: "/users_rents", local: true do |form| %>
  <div class="container ui">
    <%= form.check_box :unprocessed, checked: to_checked(params[:unprocessed]) %>
    <%= form.label :unprocessed, "feldolgozatlan", class: 'item filteroption' %>

    <%= form.check_box :approved, checked: to_checked(params[:approved]) %>
    <%= form.label :approved, "engedélyezve", class: 'item filteroption' %>

    <%= form.check_box :rejected, checked: to_checked(params[:rejected]) %>
    <%= form.label :rejected, "elutasítva", class: 'item filteroption' %>

    <%= form.check_box :taken, checked: to_checked(params[:taken]) %>
    <%= form.label :taken, "kiadva", class: 'item filteroption' %>

    <%= form.check_box :returned, checked: to_checked(params[:returned]) %>
    <%= form.label :returned, "visszavéve", class: 'item filteroption' %>

  </div>
  <br>
  <%= form.submit "Szűrés", class: "ui button primary" %>
<% end %>

<table class="ui celled table">
  <thead>
  <tr>
    <th>Eszköz</th>
    <th>Darabszám</th>
    <th>Kezdet</th>
    <th>Vége</th>
    <th>Állapot</th>
  </tr>
  </thead>

  <tbody>
  <% @rents.each do |rent| %>
    <tr>
      <td><%= rent.item.name %></td>
      <td><%= rent.number %> darab</td>
      <td><%= rent.begin.strftime("%Y.%m.%d. %H:%M") %></td>
      <td><%= rent.end.strftime("%Y.%m.%d. %H:%M") %></td>
      <td><%= I18n.t :"rent_states.#{rent.state}" %></td>
    </tr>
  <% end %>
  </tbody>
</table>