config/routes.rb
Rails.application.routes.draw do
  resources :rents, only: [:new, :index, :create]
  get 'users_rents', to: 'rents#users_index'
  post 'users_rents', to: 'rents#users_index'
  post 'rents_index', to: 'rents#index'

  post 'approve', to: 'rents#approve'
  post 'reject', to: 'rents#reject'
  post 'take', to: 'rents#take'
  post 'return', to: 'rents#return'
  resources :items, only: [:new, :index, :create, :edit, :destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :pages, only: [:show, :edit, :update]
  resources :events do
    resources :entries, only: [:create, :destroy] do
      put '/', to: 'entries#toggle_showed_up'
    end
  end
  resources :teams do
    resources :memberships do
      put '/approve', to: 'memberships#approve'
      delete '/decline', to: 'memberships#decline'
      delete '/destroy', to: 'memberships#destroy'
    end
  end
  resources :users, only: [:index, :show, :edit, :update] do
    post :set_animation, on: :collection
  end
  resources :articles
  resources :images, only: [:create]

  get '/', to: 'home#index'

  post '/logout', to: 'sessions#destroy', as: :logout
  get '/login', to: 'sessions#new', as: :login
  get '/auth/oauth/callback', to: 'sessions#create'

  scope :email do
    get '/login', to: 'session_with_email#login_page', as: :email_login_page
    post '/login', to: 'session_with_email#login', as: :email_login
    get '/registration', to: 'session_with_email#registration_page', as: :email_registration_page
    post '/registration', to: 'session_with_email#registration', as: :email_registration
  end
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root to: redirect('/')
end

app/models/event.rb
class Event < ApplicationRecord
  include ImageHelper

  has_many :entry
  has_one_attached :image

  def entered?(team)
    team.entered_for?(self)
  end

  def users_team_can_entry?(current_user)
     self.users_memberships(current_user)&.any? && self.can_entry?
  end

  def users_memberships(current_user)
    return unless current_user
    current_user&.memberships.select { |m| !entered?(m.team) && m.active? }
  end

  def can_entry?
    Time.now < self.application_deadline
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.order(created_at: :desc).all
  end

  def show
    @entry = Entry.new
    @teams = Team.where(id:@event.entry.map(&:team_id))
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :image, :intro, :content, :application_deadline, :event_date)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="ui form">
    <div class="field">
      <%= form.label :name, 'Cím' %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :image, 'Kép' %>
      <%= form.file_field :image %>
    </div>

    <div class="field">
      <%= form.label :intro, 'Bevezető szöveg' %>
      <%= form.text_area :intro, :rows => '2' %>
    </div>

    <div class="field">
      <%= form.label :content, 'Tartalom' %>
      <%= form.trix_editor :content %>
    </div>
  </div>

    <div class="field date-field">
      <%= form.label :application_deadline, 'Jelentkezési határidő:' %>
      <%= form.datetime_select :application_deadline %>
    </div>

    <div class="field date-field">
      <%= form.label :event_date, 'Esemény időpontja:' %>
      <%= form.datetime_select :event_date %>
    </div>

    <div class="actions">
      <%= form.submit 'Mentés', class: 'ui button' %>
    </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<h1>Események</h1>

<%= link_to 'Új esemény', new_event_path, :class => "ui button primary" if admin? %>

<% @events.each do |event| %>
  <div class="ui segment red stackable two column grid">
    <div class="image four wide column">
      <%= image_tag(event.thumb, alt: 'Image') if event.image? %>
    </div>
    <div class="content twelve wide column">
      <h2>
        <%= event.name %>
        <span class="meta floated right"> <%= time_ago_in_words event.created_at %></span>
      </h2>
      <p><%= event.intro %></p>
      <%= link_to 'Tovább', event, :class => "ui button right floated" %>
      <% if current_user&.admin? %>
        <%= link_to 'Szerkesztés', edit_event_path(event), :class => "ui button" %>
        <%= link_to 'Törlés', event, method: :delete, data: { confirm: 'Biztosan törlöd?' }, :class => "ui button negative" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/events/new.html.erb
<h1>Új esemény</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<h1>
  <%= @event.name %>
</h1>
<div class="wrapper">
  <div class="event-content">
    <p>
      <strong>
        <%= @event.intro %>
      </strong>
    </p>

    <p>
      <%= @event.content.html_safe %>
    </p>
    <% if current_user&.admin? %>
      <%= link_to 'Szerkesztés', edit_event_path(@event), class: 'ui button' if admin? %>
    <% end %>
  </div>
    <div class="event-applied-teams">
      <h3 class="applied-teams-title">Nevezett csapatok</h3>
      <div class="ui centered cards">
        <% @teams.each do |team| %>
          <%entry = team.entry_for(@event) %>
          <div class="ui card">
            <div class="image">
              <% if team.image? %>
                <%= image_tag(team.image.url(:square_thumb), alt: 'Image') %>
              <% else %>
                <%= image_tag('team-placeholder.png', alt: 'Image') %>
              <% end %>
            </div>
            <div class="content">
              <div class="header">
                <%= link_to team.name, team_path(team), class: 'item team-name-item' %>
              </div>
              <% if admin? %>
                <div class="description">
                  
                </div>
              <% end %>
              <% if @event.can_entry? && entry.revocable_by?(current_user) %>
                <%= link_to [@event, entry], method: :delete do %>
                  <div class="extra content">
                    <div class="ui two buttons">
                      <div class="ui basic red button">
                        Visszavonás
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
              <% if admin? %>
                <div class="extra content">
                  <div class="ui grid row">
                    <div class="eight wide column">
                      Megjelent
                    </div>
                    <div class="eight wide column right aligned">
                      <div class="ui toggle checkbox">
                        <%= check_box_tag 'showed_up', 'showed_up', entry.showed_up, class: 'showed-up', entry: entry.id, event: @event.id %>
                        <label></label>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
        <% end %>
      </div>

      <% if @event.users_team_can_entry?(current_user) %>
        <%= form_for @entry, url: event_entries_path(@event), method: 'post', :html => {class: 'ui form'} do |form| %>
        <div class="fields entry-form">
          <div class="field">
            <%= form.select 'team_id', @event.users_memberships(current_user).collect {|m| [ m.team.name, m.team.id ] },
              { include_blank: true }, class: 'ui dropdown'  %>
          </div>
          <div class="field">
            <%= form.text_area :comment, :rows => '1', :placeholder => 'Megjegyzés' %>
          </div>
          <div class="field">
            <%= form.submit 'Csatlakozás', class: 'ui button' %>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>

  <div class="event-deadlines">
    <p>
      <strong>Jelentkezési határidő</strong>
    </p>
    <h3 class="datetime-text">
      <%= @event.application_deadline.strftime('%Y. %-m. %d. %H:%M') %>
    </h3>
    <br>
    <p>
      <strong>Esemény időpontja</strong>
    </p>
    <h3 class="datetime-text">
      <%= @event.event_date.strftime('%Y. %-m. %d. %H:%M') %>
    </h3>
  </div>
</div>