config/routes.rb
Rails.application.routes.draw do
  resources :rents, only: [:new, :index, :create]
  get 'users_rents', to: 'rents#users_index'
  post 'users_rents', to: 'rents#users_index'
  post 'rents_index', to: 'rents#index'

  post 'approve', to: 'rents#approve'
  post 'reject', to: 'rents#reject'
  post 'take', to: 'rents#take'
  post 'return', to: 'rents#return'
  resources :items, only: [:new, :index, :create, :edit, :destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :pages, only: [:show, :edit, :update]
  resources :events do
    resources :entries, only: [:create, :destroy] do
      put '/', to: 'entries#toggle_showed_up'
    end
  end
  resources :teams do
    resources :memberships do
      put '/approve', to: 'memberships#approve'
      delete '/decline', to: 'memberships#decline'
      delete '/destroy', to: 'memberships#destroy'
    end
  end
  resources :users, only: [:index, :show, :edit, :update] do
    post :set_animation, on: :collection
  end
  resources :articles
  resources :images, only: [:create]

  get '/', to: 'home#index'

  post '/logout', to: 'sessions#destroy', as: :logout
  get '/login', to: 'sessions#new', as: :login
  get '/auth/oauth/callback', to: 'sessions#create'

  scope :email do
    get '/login', to: 'session_with_email#login_page', as: :email_login_page
    post '/login', to: 'session_with_email#login', as: :email_login
    get '/registration', to: 'session_with_email#registration_page', as: :email_registration_page
    post '/registration', to: 'session_with_email#registration', as: :email_registration
  end
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root to: redirect('/')
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  def require_login
    unless logged_in?
      session[:redirect_url] = request.original_fullpath
      redirect_to root_url
    end
  end

  def require_admin
    redirect_to root_url unless logged_in? && current_user.admin?
  end

  def forbidden_page
    render 'application/403', status: :forbidden
  end

  def logged_in?
    session[:user_id]
  end
  helper_method :logged_in?

  def current_user
    @current_user ||= User.includes([ { memberships: [ :team ] } ]).find(session[:user_id]) if logged_in?
  end
  helper_method :current_user

  def admin?
    current_user&.admin?
  end
  helper_method :admin?

  def can_update_user?(user)
    current_user&.admin? || user.id == current_user&.id
  end
  helper_method :can_update_user?

  def sing_in
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def oauth_login_path
    '/auth/oauth'
  end
end

app/views/application/403.html.erb
<h1>Nem vagy jogosult ennek a funkciónak a használatához!</h1>

app/views/application/_footer.html.erb
<div class="ui inverted vertical footer segment">
  <div class="ui center aligned container">
    <div class="ui inverted section divider"></div>
    <a href="http://kir-dev.sch.bme.hu" target="_blank">
      <img class="ui centered mini image" src="/images/kirdev.png">
    </a>
    <div class="ui horizontal inverted small divided link list">
      <a class="item" href="https://www.facebook.com/schorpong/">
        <i class="icon facebook"></i>Schörpong
      </a>
      <a class="item" href="mailto:schorpong@sch.bme.hu">
        <i class="icon mail"></i>schorpong@sch.bme.hu
      </a>
    </div>
    <div class="ui inverted section"></div>
  </div>
</div>

app/views/application/_navbar.html.erb
<div class="ui top fixed menu stackable inverted">
  <div class="container ui">
    <%= link_to "Hírek", articles_path, :class => "item" %>
    <%= link_to "Események", events_path, :class => "item" %>
    <div class="ui dropdown item">
      Kölcsönzés
      <div class="menu">
        <%= link_to "Eszközök", "/items", :class => "item" %>
        <%= link_to "Kölcsönzéseim", users_rents_path, :class => "item" if logged_in? %>
        <%= link_to "Összes kölcsönzés", rents_path, :class => "item" if admin? %>
      </div>
    </div>
    <%= link_to "Kölcsönzés leírás", "/pages/rents", :class => "item" %>
    <%= link_to "Rólunk", "/pages/about", :class => "item" %>
    <%= link_to "Szabályok", "/pages/rules", :class => "item" %>
    <%= link_to "Csapatok", teams_path, :class => "item" %>
    <div class="right menu">
      <% if logged_in? %>
        <div class="ui dropdown item">
          <%= current_user.name %>
          <div class="menu">
            <%= link_to "Profilom", user_path(current_user), :class => "item" %>
            <%= link_to "Felhasználók", users_path, :class => "item" if admin? %>
            <%= link_to "Kijelentkezés", logout_path, :class => "item", :method => :post %>
          </div>
        </div>
        <div class="item">
          <a class="anim">Animáció</a>
          <label class="switch">
            <input type="checkbox" id="toggle_visited"
                   <% if current_user.animation_enabled? %>checked
                   <% end %>
                   onclick="toggleAnimationHandler(this)">
            <span class="slider round"></span>
          </label>
        </div>
      <% else %>
        <div class="ui dropdown item">
          <a>Bejelentkezés</a>
          <div class="menu">
            <%= link_to "AuthSCH-s Bejelentkezés", oauth_login_path, :class => "item", method: :post %>
            <%= link_to "Email-es Bejelentkezés", email_login_page_path, :class => "item" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/application/sign_in.html.erb
  <%= tag.h1 :Belépés,class:'ui header'%>

<%= form_tag session_for_registered_path,class:'ui form' do %>
   <%= label_tag :mail%>
   <%= text_field_tag :mail %>
   <br>
   <%= label_tag :password%>
   <%= password_field_tag :password%>
   <br>
   <%= submit_tag 'Belépés', class:'ui button'%>
<%end%>

<%= link_to 'AutSCH',oauth_login_path %>
<br>
<%= link_to 'Regisztráció',new_registration_path %>